### ISSUE TITLE
Invalid character in header content ["WWW-Authenticate"]

### ISSUE THREAD

**Issue by kiliankoe** [djmaze/tiddlywiki-docker#10]
This works great on my machine, but running it on a VM keeps bringing up this error. I've tried not passing the basic auth credentials (and letting my reverse-proxy take care of that), unfortunately that doesn't help. I'm starting to run out of ideas, maybe someone else can help? 🙈 Thanks!

```
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["WWW-Authenticate"]
    app_1  |     at storeHeader (_http_outgoing.js:412:5)
    app_1  |     at processHeader (_http_outgoing.js:407:3)
    app_1  |     at ServerResponse._storeHeader (_http_outgoing.js:313:9)
    app_1  |     at ServerResponse.writeHead (_http_server.js:270:8)
    app_1  |     at SimpleServer.requestHandler ($:/core/modules/commands/server.js:110:13)
    app_1  |     at Server.emit (events.js:182:13)
    app_1  |     at parserOnIncoming (_http_server.js:658:12)
    app_1  |     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

**Comment by kiliankoe** [comment]
Ah, I've managed to solve this by explicitly passing empty strings to the tiddlywiki node cli for the auth parameters 🎉 Now my reverse-proxy can take care of authentication and the rest is running. Thanks so much for putting this image together! 😊
